#!/bin/bash
read -p $'Do you want to overwrite ~/.nanorc ? Y/N\nWarning, you might end up with duplicate "include" otherwise.\n' -n 1
echo;echo
if [[ $REPLY =~ ^[Yy]$ ]]; then rm $HOME/.nanorc; fi
for file in /usr/share/nano/*.nanorc;
    do
        echo "include $file" >> $HOME/.nanorc;
    done
cat $HOME/.nanorc